name: run-tests

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 
  test:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-20.04]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .
    - name: Check with pytest
      run: |
        pytest testfile.py
